---
- hosts: all
  become: true
  become_method: su
  tasks:
   - name: Add repository
     yum_repository:
        name: cjt
        description: CloudBees Jenkins Team YUM repo
        baseurl: https://downloads.cloudbees.com/cjt/rolling/rpm
        gpgcheck: yes
   - rpm_key:
      state: present
      key: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x38E2F5F39FF90BDA
   - name: install the latest version of JDK
     yum:
       name: java-1.8.0-openjdk
       state: latest    
   - name: install the latest version of CJT
     yum:
       name: cjt
       state: latest
       # PULLED NSUPDATE Module lines, will work at user-data
  # - name: Add or modify hostname.jenkins.northwestern.edu A to 10.28.129.128/28"
  #   nsupdate:
   #   server: "129.105.49.1"
    #  zone: "jenkins.northwestern.edu"
    #  record: "jpw-test-7"
     # value: "10.28.129.132"